# Generated by Django 2.2.5 on 2019-10-11 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='nome',
            field=models.TextField(blank=True, null=True),
        ),
    ]
