# Generated by Django 2.2.5 on 2019-10-08 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipamentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetornoImagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Automovel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(blank=True, max_length=150, null=True)),
                ('ufPlaca', models.CharField(blank=True, max_length=15, null=True)),
                ('chassi', models.CharField(blank=True, max_length=150, null=True)),
                ('renavam', models.CharField(blank=True, max_length=150, null=True)),
                ('marcaModelo', models.CharField(blank=True, max_length=150, null=True)),
                ('anoDoVeiculo', models.CharField(blank=True, max_length=4, null=True)),
                ('km', models.CharField(blank=True, max_length=15, null=True)),
                ('cor', models.CharField(blank=True, max_length=100, null=True)),
                ('combustivel', models.CharField(blank=True, max_length=100, null=True)),
                ('tipoVeiculo', models.CharField(blank=True, max_length=100, null=True)),
                ('capacidadePassageiros', models.CharField(blank=True, max_length=3, null=True)),
                ('fabricante', models.CharField(blank=True, max_length=100, null=True)),
                ('fotoCNH', models.ImageField(blank=True, null=True, upload_to='fotoRecibo')),
                ('fotoCRLV', models.ImageField(blank=True, null=True, upload_to='fotoRecibo')),
                ('fotoDianteiraDireita', models.ImageField(blank=True, null=True, upload_to='fotoRecibo')),
                ('fotoDianteiraEsquerda', models.ImageField(blank=True, null=True, upload_to='fotoRecibo')),
                ('fotoTraseiraDireita', models.ImageField(blank=True, null=True, upload_to='fotoRecibo')),
                ('fotoTraseiraEsquerda', models.ImageField(blank=True, null=True, upload_to='fotoRecibo')),
                ('equipamentos', models.ManyToManyField(to='equipamentos.Equipamento')),
            ],
        ),
    ]
