# Generated by Django 2.2.5 on 2019-10-09 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automovel', '0002_retornocrlv'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RetornoCRLV',
        ),
    ]
