# Generated by Django 2.2.5 on 2019-10-11 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automovel', '0003_delete_retornocrlv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automovel',
            name='equipamentos',
            field=models.ManyToManyField(blank=True, null=True, to='equipamentos.Equipamento'),
        ),
        migrations.AlterField(
            model_name='automovel',
            name='fotoCNH',
            field=models.ImageField(blank=True, null=True, upload_to='fotoCNH'),
        ),
        migrations.AlterField(
            model_name='automovel',
            name='fotoCRLV',
            field=models.ImageField(blank=True, null=True, upload_to='fotoCRLV'),
        ),
        migrations.AlterField(
            model_name='automovel',
            name='fotoDianteiraDireita',
            field=models.ImageField(blank=True, null=True, upload_to='fotoDianteiraDireita'),
        ),
        migrations.AlterField(
            model_name='automovel',
            name='fotoDianteiraEsquerda',
            field=models.ImageField(blank=True, null=True, upload_to='fotoDianteiraEsquerda'),
        ),
        migrations.AlterField(
            model_name='automovel',
            name='fotoTraseiraDireita',
            field=models.ImageField(blank=True, null=True, upload_to='fotoTraseiraDireita'),
        ),
        migrations.AlterField(
            model_name='automovel',
            name='fotoTraseiraEsquerda',
            field=models.ImageField(blank=True, null=True, upload_to='fotoTraseiraEsquerda'),
        ),
    ]
