# Generated by Django 2.2.5 on 2019-10-11 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automovel', '0005_auto_20191011_1847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automovel',
            name='equipamentos',
        ),
    ]
