# Generated by Django 2.2.5 on 2019-10-16 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataRegistro', models.DateTimeField(auto_now_add=True)),
                ('quantidade_quartos', models.IntegerField(blank=True, null=True)),
                ('quantidade_salas', models.IntegerField(blank=True, null=True)),
                ('quantidade_cozinha', models.IntegerField(blank=True, null=True)),
                ('quantidade_banheiro', models.IntegerField(blank=True, null=True)),
                ('quantidade_quintal', models.IntegerField(blank=True, null=True)),
                ('fotoSala', models.ImageField(blank=True, null=True, upload_to='fotoSala')),
                ('fotoQuarto', models.ImageField(blank=True, null=True, upload_to='fotoQuarto')),
                ('fotoBanheiro', models.ImageField(blank=True, null=True, upload_to='fotoBanheiro')),
                ('fotoCozinha', models.ImageField(blank=True, null=True, upload_to='fotoCozinha')),
            ],
        ),
    ]
