# Generated by Django 2.2.5 on 2019-10-16 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documentos_pessoais_imoveis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vistoria_Imoveis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('documentosPessoais', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='documentos_pessoais_imoveis.DocumentosPessoaisImoveis')),
            ],
        ),
    ]
