# Generated by Django 2.2.5 on 2019-10-16 18:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('imovel', '0001_initial'),
        ('endereco', '0001_initial'),
        ('vistoria_imoveis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vistoria_imoveis',
            name='dataRegistro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vistoria_imoveis',
            name='endereco',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='endereco.Endereco'),
        ),
        migrations.AddField(
            model_name='vistoria_imoveis',
            name='imovel',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='imovel.Imovel'),
        ),
    ]
