# Generated by Django 2.2.5 on 2019-10-08 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('automovel', '0001_initial'),
        ('documentosPessoais', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vistoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('automovel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='automovel.Automovel')),
                ('documentosPessoais', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='documentosPessoais.DocumentosPessoais')),
            ],
        ),
    ]
