# Generated by Django 2.2.5 on 2019-10-10 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vistoria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vistoria',
            name='documentosPessoais',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='documentosPessoais.DocumentosPessoais'),
        ),
    ]
