# Generated by Django 2.2.5 on 2019-10-16 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentosPessoaisImoveis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('cpf', models.CharField(max_length=15)),
                ('dataRegistro', models.DateTimeField(auto_now_add=True)),
                ('email', models.CharField(blank=True, max_length=150, null=True)),
                ('dataNascimento', models.CharField(blank=True, max_length=150, null=True)),
                ('telefone', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
