# Generated by Django 2.2.5 on 2019-10-09 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentosPessoais', '0002_retornorecibo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RetornoRecibo',
        ),
    ]
