# Generated by Django 2.2.5 on 2019-10-09 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documentosPessoais', '0006_auto_20191009_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentospessoais',
            name='endereco',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='endereco.Endereco'),
        ),
    ]
