# Generated by Django 2.2.5 on 2019-10-09 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentosPessoais', '0007_auto_20191009_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentospessoais',
            name='dataNascimento',
            field=models.CharField(max_length=150),
        ),
    ]
