# Generated by Django 2.2.5 on 2019-10-11 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentosPessoais', '0008_auto_20191009_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentospessoais',
            name='telefone',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
